[package]
name = "ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.5"
serde = "1.0.188"
sled = "0.34.7"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
