name: AI repo test run
on:
  push:
    branches: [ main ]
  pull:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rust:latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build the rust bin
        run: cargo build --verbose
      - name: run the tests
        run: cargo test --verbose
